### ISSUE TITLE
Missing Copyright Notice and License to Uhaha

### ISSUE THREAD

**Issue by tidwall** [gitsrc/IceFireDB#26]
Hi, 

The source code in the [rafthub](https://github.com/gitsrc/IceFireDB/tree/main/rafthub) directory of this project is directly copied from https://github.com/tidwall/uhaha/blob/master/uhaha.go, which is 3K+ lines of original source code written and copyrighted by me. 

The original [copyright notice](https://github.com/tidwall/uhaha/blob/master/uhaha.go#L1) and [LICENSE](https://github.com/tidwall/uhaha/blob/master/LICENSE) were omitted.

The Uhaha LICENSE states: 

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by gitsrc** [comment]
Ok I will add it later

**Comment by gitsrc** [comment]
> Hi,
> 
> The source code in the [rafthub](https://github.com/gitsrc/IceFireDB/tree/main/rafthub) directory of this project is directly copied from https://github.com/tidwall/uhaha/blob/master/uhaha.go, which is 3K+ lines of original source code written and copyrighted by me.
> 
> The original [copyright notice](https://github.com/tidwall/uhaha/blob/master/uhaha.go#L1) and [LICENSE](https://github.com/tidwall/uhaha/blob/master/LICENSE) were omitted.
> 
> The Uhaha LICENSE states:
> 
> > The above copyright notice and this permission notice shall be included in all
> > copies or substantial portions of the Software.

IceFireDB stands on the shoulders of the giant uhaha. I will adjust and restore uhaha's copyright and agreement at the fastest speed. I apologize to you and hope to be inclusive.

**Comment by gitsrc** [comment]
> Hi,
> 
> The source code in the [rafthub](https://github.com/gitsrc/IceFireDB/tree/main/rafthub) directory of this project is directly copied from https://github.com/tidwall/uhaha/blob/master/uhaha.go, which is 3K+ lines of original source code written and copyrighted by me.
> 
> The original [copyright notice](https://github.com/tidwall/uhaha/blob/master/uhaha.go#L1) and [LICENSE](https://github.com/tidwall/uhaha/blob/master/LICENSE) were omitted.
> 
> The Uhaha LICENSE states:
> 
> > The above copyright notice and this permission notice shall be included in all
> > copies or substantial portions of the Software.

I finished the adjustment with the fastest speed. I have merged the master branch. Please forgive the negligence of the open source novice, and once again declare that IceFireDB stands on the shoulders of uhaha,
And thanks for the outstanding contribution of the uhaha project

**Comment by gitsrc** [comment]
> Hi,
> 
> The source code in the [rafthub](https://github.com/gitsrc/IceFireDB/tree/main/rafthub) directory of this project is directly copied from https://github.com/tidwall/uhaha/blob/master/uhaha.go, which is 3K+ lines of original source code written and copyrighted by me.
> 
> The original [copyright notice](https://github.com/tidwall/uhaha/blob/master/uhaha.go#L1) and [LICENSE](https://github.com/tidwall/uhaha/blob/master/LICENSE) were omitted.
> 
> The Uhaha LICENSE states:
> 
> > The above copyright notice and this permission notice shall be included in all
> > copies or substantial portions of the Software.

If you still need to adjust, please feel free to contact me
