### ISSUE TITLE
Neat idea, but need more documentation

### ISSUE THREAD

**Issue by Pyrolistical** [gitsrc/IceFireDB#29]
I want to understand what is the architecture. What is the process of configuring, adding, removing nodes?

How was raft integrated with redis, IE. where was raft end and redis begin?

**Comment by gitsrc** [comment]
> I want to understand what is the architecture. What is the process of configuring, adding, removing nodes?
> 
> How was raft integrated with redis, IE. where was raft end and redis begin?

Okay, I will add relevant documents to the project. The current project is still in the development stage.  IceFireDB currently includes the raft protocol, resp protocol server, persistent storage and other parts. User traffic first goes to the resp server and then to the raft network. After receiving the request, each node executes the write or query of the underlying storage and returns it to the user. I will simply  Explain the relationship, thank you for your attention.

**Comment by gitsrc** [comment]
At present, the open source community has some persistent kv + redis server implementation projects. IcefireDB is firstly different from other projects in the consistency guarantee method. The project is guaranteed through the raft strong consistency framework, which is different from the semi-synchronization of most schemes, so it has more  High consistency.  The project Ice stands for disk storage and Fire stands for memory storage. It will build a layer of hot and cold data hybrid structure to help users achieve some balance between storage cost and performance. Let’s talk a little more. IceFireDB will then design on the current single-group raft structure.  Multi-group raft structure, and use consistent hash ring algorithm + redis resp proxy user-side data fragmentation, user-side business code basically does not need to be changed, and proxy can be used to realize the expansion and shrinkage awareness and read and write of the IceFireDB cluster.
