### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by carr123** [gitsrc/IceFireDB#44]
is there any config file ?
how to start a cluster ?
thanks.

**Comment by gitsrc** [comment]
> is there any config file ?
> how to start a cluster ?
> thanks.

Now, you can use the -h command parameter to learn how to run, there is no manual yet, thank you for your attention.

**Comment by carr123** [comment]
@gitsrc thanks you.
one more question, if i add more servers to a cluster, is there any resharding of keys happen ?

**Comment by gitsrc** [comment]
> @gitsrc thanks you.
> one more question, if i add more servers to a cluster, is there any resharding of keys happen ?

At present, only single-group raft is supported. There will be no key redistribution in the single-group raft scenario. The distributed horizontal expansion of multiple groups of raft. At present, there are partners in the community who are interested in submitting relevant codes. Follow-up will be released, and you are welcome to continue to pay attention.

**Comment by carr123** [comment]
thanks.
